### ISSUE TITLE
Update example to use reverse port forwarding

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/EXAMPLES-Java-Standalone-and-Android-AltTrashCat#3]
## Description
 
Change in the setup the port forwarding with reverse port forwarding

## Additional info
- epic: https://github.com/alttester/AltTester-Unity-SDK/issues/1139
- the PR for this issue should be merged on the `main` branch only when we have the released tester for pro 1.0

**Comment by MihaiCuc98** [comment]
Tests results:
- Android:
![image](https://github.com/alttester/EXAMPLES-Java-Standalone-and-Android-AltTrashCat/assets/113912901/e0b3986a-0b01-4c55-bd98-4c1f34f729d0)
- Standalone:
![image](https://github.com/alttester/EXAMPLES-Java-Standalone-and-Android-AltTrashCat/assets/113912901/ccf57ce4-903f-4e87-9963-86802cbda71d)

I will move this ticket into `Done`.
